name: Run Tkinter Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tkinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk xvfb
          python -m pip install --upgrade pip
          # Add any required pip packages below
          pip install numpy pillow
          pip install paho-mqtt tkinter

      - name: Run Tkinter script
        run: |
          nohup Xvfb :99 -screen 0 1280x1024x24 &
          export DISPLAY=:99
          python final_tkinter.py
